### ISSUE TITLE
Youtube link regex doesn't work with long ID links

### ISSUE THREAD

**Issue by math-98** [cjmaxik/TruckersMP_Improved#15]
https://www.youtube.com/watch?v=M65wmvaMfrg <- Not working link
https://www.youtube.com/watch?v=yhyjYZlZSNE <- Working

I assume it's because of the ID being longer than before

**Comment by cjmaxik** [comment]
@math-98, this links are identical in terms of characters count. Also, regex is normal.
Please, show me example of this bug (also any console logs).

**Comment by math-98** [comment]
The problem seems to appear only on the report I sent and I don't see why.
I'm currently investigating on the _youtubepopup.js_ file as I believe it's the faulty here

**Comment by math-98** [comment]
After some researches found out this problem was due to a reporter mistake
-> Not a bug
