### ISSUE TITLE
Links from img.youtube.com having modal when they shouldn't

### ISSUE THREAD

**Issue by titanic4** [cjmaxik/TruckersMP_Improved#28]
All the links from img.youtube.com(YouTube's thumbnail server) in either reports or appeals are showing the modal. The thing is: The modal should show only for YouTube videos in case of detecting the youtube.com domain in the link. The following line in main.js: https://github.com/cjmaxik/TruckersMP_Improved/blob/07d05a77f6efbab7538113fdd9ce748b0a64e087/src/main.js#L306 is most likely causing the problem.

**Comment by math-98** [comment]
I can hotfix that by changing this line to
`if (sub.contains(["youtube.com", "youtu.be"]) && !sub.contains(["img.youtube.com"])) { `
