### ISSUE TITLE
Profile page - "Next ban" button in wrong place

### ISSUE THREAD

**Issue by cjmaxik** [cjmaxik/TruckersMP_Improved#55]
![image](https://user-images.githubusercontent.com/1501705/46590614-f4f17d80-caf7-11e8-88fb-0e122c5a1aa5.png)

**Comment by dequeues** [comment]
Sorry for delay - I cannot see that panel @cjmaxik

Can you check if `$(document).find('.profile-body .panel-profile:nth-child(4)');` selects the correct panel for you?

**Comment by dequeues** [comment]
Please test PR. @cjmaxik

**Comment by cjmaxik** [comment]
Solved, thanks. Postponed to the next update.
